Repository open-xchange/flutter-deltachat-core, pull requests merged in 2020-03, with the labels that each got.

#77 Forward state for messages #337
  android/src/main/java/com/openxchange/deltachatcore/handlers/MessageCallHandler.java
  ios/Classes/DCWrapper/DcMsg.swift
  ios/Classes/Handler/MessageCallHandler.swift
  lib/src/chatmsg.dart
Labels: warning

#78 Empty user in group profile after deletion #491
  android/src/main/java/com/openxchange/deltachatcore/handlers/ContextCallHandler.java
  ios/Classes/DCWrapper/DCContext.swift
  ios/Classes/Handler/ContextCallHandler.swift
Labels: warning

#81 OT-744: Add debug infos for DCC
  android/src/main/java/com/openxchange/deltachatcore/DeltaChatCorePlugin.java
  ios/Classes/DCWrapper/DCContext.swift
  ios/Classes/SwiftDeltaChatCorePlugin.swift
Labels: android, iOS

#79 OT-751: Sending files don't work for *.plist and *.rar
  ios/Classes/DCWrapper/DCContext.swift
  ios/Classes/DCWrapper/DCEventCallback/DCEventCallback.swift
  ios/Classes/DCWrapper/DCEventHandler.swift
  ios/Classes/DCWrapper/DcChat.swift
  ios/Classes/DCWrapper/DcMsg.swift
  ios/Classes/DCWrapper/Model/Media.swift
  ios/Classes/DCWrapper/Model/Message.swift
  ios/Classes/Handler/ChatCallHandler.swift
  ios/Classes/Handler/ContextCallHandler.swift
Labels: bug, iOS

#80 Enable file logging #494
  android/src/main/java/com/openxchange/deltachatcore/ConnectivityReceiver.java
  android/src/main/java/com/openxchange/deltachatcore/DeltaChatCorePlugin.java
  android/src/main/java/com/openxchange/deltachatcore/NativeInteractionManager.java
  android/src/main/java/com/openxchange/deltachatcore/Utils.java
  android/src/main/java/com/openxchange/deltachatcore/handlers/EventChannelHandler.java
  ios/Classes/DCWrapper/DCContext.swift
  ios/Classes/DCWrapper/DCEventCallback/DCEventCallback.swift
  ios/Classes/DCWrapper/DCEventHandler.swift
  ios/Classes/DCWrapper/DcMsg.swift
  ios/Classes/Handler/ChatCallHandler.swift
  ios/Classes/Handler/ChatListCallHandler.swift
  ios/Classes/Handler/ContactCallHandler.swift
  ios/Classes/Handler/ContextCallHandler.swift
  ios/Classes/Handler/MessageCallHandler.swift
  ios/Classes/Helper/Utils.swift
  ios/Classes/SwiftDeltaChatCorePlugin.swift
Labels: warning
